[database]
connection = "mysql"
server = "127.0.0.1"
port = "3306"
database = "khankhulgun"
user = "root"
password = ""

[app]
name = "Virtual Platform"
port = ":80"
migrate = "true"
seed = "true"

[superadmin]
login = "superadmin"
password = "superadmin"
email = "munkaltai@gmail.com"

[JWT]
secret="<%= secretKey %>"
ttl=2160

[mail]
driver="smtp"
host="smtp.gmail.com"
port=587
username=""
password=""
encryption="tls"

[lambdaconfig]
configfile = "lambda.json"